### ISSUE TITLE
"double free or corruption" with --test after krb5-18

### ISSUE THREAD

**Issue by carlmon** [openwall/john#4039]
I get the following error when running `john -test` on an Azure NV12 instance with updated Ubuntu 18.04 LTS and GRID drivers.

> *** Error in `/snap/john-the-ripper/297/run/john': double free or corruption (out): 0x0000000004a404f0 ***

The error is repeatable (I tried 3 times) and occurs at the same place during the benchmark. See attached files for details.

[Build Info.txt](https://github.com/magnumripper/JohnTheRipper/files/3338150/Build.Info.txt)
[Error Dump.txt](https://github.com/magnumripper/JohnTheRipper/files/3338151/Error.Dump.txt)
[Output before crash.txt](https://github.com/magnumripper/JohnTheRipper/files/3338152/Output.before.crash.txt)

The Azure VM can be replicated with this template if needed: https://github.com/carlmon/Hashcat-Azure

**Comment by carlmon** [comment]
I get the same error when building `bleeding-jumbo` from source using the `INSTALL-UBUNTU` steps. Last lines from `./john --test=0` in the `~/src/john/run` path:
> Testing: krb5-17, Kerberos 5 DB etype 17 [DES / PBKDF2-SHA1 256/256 AVX2 8x AES]... (12xOMP) PASS
> Testing: krb5-18, Kerberos 5 DB etype 18 [DES / PBKDF2-SHA1 256/256 AVX2 8x AES]... (12xOMP) PASS
> double free or corruption (out)
> Aborted (core dumped)

**Comment by ghost** [comment]
Please, anyone with hardware available, reproduce this using gdb to get a backtrace. 

Using an Ubuntu 16.04 VM [1] it works, even inside Azure [2]. I guess it is a bug catched or triggered by new libc, or gcc 5.4 versus 7.4, ...

[1] https://travis-ci.org/claudioandre-br/JohnTheRipper/jobs/547863536
[2] no real link, but it is my build id 144 (inside Acceptance Test).
****
**[edited]** 
* I added a new test using Ubuntu 18.04 on Docker inside Azure;
  * I don't want to create and store a new VM and pay for it.
* It also works; therefore, a 18.04 test inside Docker on top of a 16.04 VM works.
* (My conclusion) the error happens only on a full Ubuntu 18.04 stack.

**Comment by solardiz** [comment]
@carlmon It's weird you were getting these errors when we were not, but regardless can you please try again with our latest bleeding-jumbo? We did fix some other bugs, and who knows what memory corruption might have been causing the behavior you saw - maybe it's gone with our other fixes. Thanks.

Edit: also, if the same crash still happens, can you please try testing `--format=krb5-18` separately? Also try both (all-formats test and one format test) with `OMP_NUM_THREADS=1`.

**Comment by solardiz** [comment]
Added milestone because this is _potentially_ a bug for us to fix, even though in my recent testing with ASan all CPU formats passed. (I ran that on AVX rather than AVX2, though.)

We need to somehow gain confidence this isn't our bug. It might be e.g. an OpenSSL bug, or it could be our bug in _usage_ of OpenSSL APIs (which wouldn't get caught by ASan since OpenSSL wasn't built with ASan).

**Comment by ghost** [comment]
For some time I have "builds from source" and snap tests running on Ubuntu 18.04. I haven't seen any problems so far.

**Comment by ender003** [comment]
I'm having this exact same issue. The test stops at the same place as OP, but running the test in one format works (see below). Can repeat 5x. I'm running Kali on physical Intel machine. 

```
Benchmarking: krb5-17, Kerberos 5 DB etype 17 [DES / PBKDF2-SHA1 256/256 AVX2 8x AES]... (12xOMP) DONE
Raw:	51558 c/s real, 4289 c/s virtual

Benchmarking: krb5-18, Kerberos 5 DB etype 18 [DES / PBKDF2-SHA1 256/256 AVX2 8x AES]... (12xOMP) DONE
Raw:	25734 c/s real, 2142 c/s virtual

double free or corruption (out)
zsh: abort      john -test
                                                                        
$ john -test --format=krb5-18 
Will run 12 OpenMP threads
Benchmarking: krb5-18, Kerberos 5 DB etype 18 [DES / PBKDF2-SHA1 256/256 AVX2 8x AES]... (12xOMP) DONE
Raw:	25206 c/s real, 2135 c/s virtual

apt list --installed john 
Listing... Done
john/kali-rolling,now 1.9.0-Jumbo-1-0kali3 amd64 [installed]
```

**Comment by solardiz** [comment]
@ender003 Thank you, but as you realize this is an older version of our code. Can you please test whether the issue is still present with the latest code from this repo?

**Comment by solardiz** [comment]
@ender003 Can you also try running the existing Kali build with `OMP_NUM_THREADS=1`?

```
OMP_NUM_THREADS=1 john -test
```

**Comment by ender003** [comment]
Thanks, @solardiz . 

I complied the latest bleeding-jumbo, and it worked! Thank you.
FWIW - also ran the singe thread option (OMP_NUM_THREADS=1 john -test) under the old version, and it also worked.

Thanks for you help!

**Comment by solardiz** [comment]
Thank you, @ender003. It's helpful to know the issue goes away with those changes. I only wish we knew what made it go away in our newer code.

Meanwhile, I think I just managed to reproduce a similar issue (hopefully, caused by the same bug) on CentOS 7 using the 1.9.0-jumbo-1 release and running exactly 12 AVX2 threads like we see in both reports above. Here's what I'm getting:

```
$ OMP_NUM_THREADS=12 ../run/john -test=0
[...]
Testing: krb5-17, Kerberos 5 DB etype 17 [DES / PBKDF2-SHA1 256/256 AVX2 8x AES]... (12xOMP) PASS
Testing: krb5-18, Kerberos 5 DB etype 18 [DES / PBKDF2-SHA1 256/256 AVX2 8x AES]... (12xOMP) PASS
Testing: krb5-3, Kerberos 5 DB etype 3 [DES / PBKDF2-SHA1 256/256 AVX2 8x AES]... (12xOMP) Segmentation fault
```

This is actually on an 8-thread CPU here. There's no crash when running 8 threads. There is with 12. We'll need to narrow this down further.

**Comment by solardiz** [comment]
Here's where it crashes for me, but perhaps the memory corruption occurs somewhat earlier:

```
Testing: krb5-18, Kerberos 5 DB etype 18 [DES / PBKDF2-SHA1 256/256 AVX2 8x AES]... (12xOMP) PASS
Testing: krb5-3, Kerberos 5 DB etype 3 [DES / PBKDF2-SHA1 256/256 AVX2 8x AES]... (12xOMP) 
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff61b3c65 in _int_malloc () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.4.x86_64 gmp-6.0.0-11.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.12.2-14.el7.x86_64 libcom_err-1.42.9-7.el7.x86_64 libgomp-4.8.5-28.el7_5.1.x86_64 libselinux-2.2.2-6.el7.x86_64 nss-softokn-freebl-3.28.3-8.el7_4.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 pcre-8.32-14.el7.x86_64 xz-libs-5.1.2-9alpha.el7.x86_64 zlib-1.2.7-13.el7.x86_64
(gdb) bt
#0  0x00007ffff61b3c65 in _int_malloc () from /lib64/libc.so.6
#1  0x00007ffff61b6a14 in calloc () from /lib64/libc.so.6
#2  0x00000000006b55dc in mem_calloc (nmemb=nmemb@entry=1048576, size=size@entry=8) at memory.c:91
#3  0x00000000006a7046 in ldr_init_database (db=db@entry=0x40a48b0, db_options=0x215ac10 <options+16>) at loader.c:296
#4  0x00000000006aa6c9 in ldr_init_test_db (format=format@entry=0xc6fe60 <fmt_krb5_3>, real=real@entry=0x0) at loader.c:1222
#5  0x000000000068e1b5 in benchmark_all () at bench.c:881
```

**Comment by solardiz** [comment]
Reverting the relevant hunk of 6738a9dc27031b444cdd91d9fe9252e4d468a175 does _not_ make the problem reappear on our current code for me. So I still don't know what made it disappear.

**Comment by solardiz** [comment]
Still reproducible on a 20190620 build, not reproducible on 20200228. (Using whatever builds I had lying around on that machine.)
