### ISSUE TITLE
mask with a lot (>260) of ranges/placeholders crashes with sigsegv/segfault

### ISSUE THREAD

**Issue by AlekseyCherepanov** [openwall/john#4115]
Actually @rofl0r has found it.

The crash:
```
$ gdb ./JohnTheRipper/run/john
[...]
(gdb) run  --mask="`python -c 'print "[ab]" * 1000'`" --stdout
[...]

Program received signal SIGSEGV, Segmentation fault.
_IO_vfscanf_internal (s=0x6bc000006b8, format=0x555555b7a917 "%lu\n", 
    argptr=argptr@entry=0x7fffffffcb98, errp=errp@entry=0x0) at vfscanf.c:347
347	vfscanf.c: Нет такого файла или каталога.
(gdb) bt
#0  _IO_vfscanf_internal (s=0x6bc000006b8, format=0x555555b7a917 "%lu\n", 
    argptr=argptr@entry=0x7fffffffcb98, errp=errp@entry=0x0) at vfscanf.c:347
#1  0x00007ffff5f78db7 in ___vfscanf (s=<optimized out>, 
    format=<optimized out>, argptr=argptr@entry=0x7fffffffcb98)
    at vfscanf.c:3066
#2  0x00007ffff5f801c7 in __fscanf (stream=stream@entry=0x6bc000006b8, 
    format=format@entry=0x555555b7a917 "%lu\n") at fscanf.c:31
#3  0x00005555558ac390 in mask_restore_state (file=0x6bc000006b8)
    at mask.c:1913
#4  0x00005555558bfb1c in rec_restore_mode (
    restore_mode=restore_mode@entry=0x5555558ac360 <mask_restore_state>)
    at recovery.c:653
#5  0x00005555558b42a6 in mask_crk_init (db=0x5555571d22a0 <database>)
    at mask.c:2446
#6  0x00005555558a4ef3 in john_run () at john.c:1941
#7  main (argc=<optimized out>, argv=<optimized out>) at john.c:2221
```

For me, the problem starts with 261 or more ranges. Ranges of single letter (e.g. `[a]`) works well. `?l` x 261 crashes too.
```
$ ./JohnTheRipper/run/john --mask="`python -c 'print "?l" * 261'`" --stdout --verbosity=1
Warning: Verbosity decreased to minimum, candidates will not be printed!
Segmentation fault
```

It crashes on `super` too.

john is quite fresh (has opencl; openmp is disabled):
```
Version: 1.9.0-jumbo-1+bleeding-ea33667eb 2019-09-23 12:43:34 +0200
Build: linux-gnu 64-bit x86_64 AVX2 AC
```

**Comment by magnumripper** [comment]
While it's a bit optimistic to use more ranges/placeholders than PLAINTEXT_LENGTH, we should obviously bail with an error instead of crash.
