### ISSUE TITLE
bitcoin2john.py ERROR parsing wallet.dat

### ISSUE THREAD

**Issue by deathmorlock** [openwall/john#4225]
Bitcoin-core wallet opens and works fine.  But cant extract hash with bitcoin2john.py
```
Traceback (most recent call last):
  File "btc.py", line 619, in parse_wallet
    d['lockTime'] = vds.read_uint32()
  File "btc.py", line 498, in read_uint32
    def read_uint32(self): return self._read_num('<I')
  File "btc.py", line 539, in _read_num
    (i,) = struct.unpack_from(format, self.input, self.read_cursor)
OverflowError: long int too large to convert to int
ERROR parsing wallet.dat, type txkey data: tx(lЁББ╣┌_DЛъ)TfцhуiыЭxx╨ф;Ж%сШ╗key data in hex: 027478286cf08181b9da5f448bea295466e61a0668e369eb9d7878d0e43b8625e198bbvalue data in hex: 0200000000010127c95af9d3e7d9ff885fa6687b67d2bc19f7df2bc7583531b4dd2d682c4cfc1b48000000171600142e4b7ba8009eb12e3501288c210f2245eafe909ffdffffff02faab4f010000000017a914596699ff33dde099f9c34d922a28ca145202276087003fab01000000001976a914d29d95238ab177fc5f304f31cb328f6e49fc02fa88ac0247304402200fe38662dbd0f1c7d877b24f74b6051213a8df937b10bf714d2472dd75c4edb50220472d97d084b50d0d02c56d1cd017940f14fa53e93531dd15b6f1560f415afbe701210359cf72c727ca59349b370254c2fe30c57f02b5afe1dd2fd36aa7541a5fc088a723ad08006ccb732240b56ff18ada26f209a84081551c70aa1c4b0e00000000000000000000190a000000030b66726f6d6163636f756e7400016e033735320974696d65736d6172740a313535333438363235370001000000b151985c0100
```

**Comment by solardiz** [comment]
@deathmorlock You're trying to use an older revision of the script that we had in the 1.9.0-jumbo-1 release. The revision that we currently have in this repo is different, containing a total of 248 lines - so it doesn't even have the line numbers you're quoting. Please upgrade.

**Comment by deathmorlock** [comment]
Hello. i donwload this one again - https://github.com/magnumripper/JohnTheRipper/archive/1.9.0-Jumbo-1.zip
and use bitcoin2john.py from it . (also i can send you wallet for tests)
```
Traceback (most recent call last):
  File "bitcoin2john.py", line 619, in parse_wallet
    d['lockTime'] = vds.read_uint32()
  File "bitcoin2john.py", line 498, in read_uint32
    def read_uint32(self): return self._read_num('<I')
  File "bitcoin2john.py", line 539, in _read_num
    (i,) = struct.unpack_from(format, self.input, self.read_cursor)
OverflowError: long int too large to convert to int
ERROR parsing wallet.dat, type txkey data: tx(lЁББ╣┌_DЛъ)TfцhуiыЭxx╨ф;Ж%сШ╗key data in hex: 027478286cf08181b9da5f448bea295466e61a0668e369eb9d7878d0e43b8625e198bbvalue data in hex: 0200000000010127c95af9d3e7d9ff885fa6687b67d2bc19f7df2bc7583531b4dd2d682c4cfc1b48000000171600142e4b7ba8009eb12e3501288c210f2245eafe909ffdffffff02faab4f010000000017a914596699ff33dde099f9c34d922a28ca145202276087003fab01000000001976a914d29d95238ab177fc5f304f31cb328f6e49fc02fa88ac0247304402200fe38662dbd0f1c7d877b24f74b6051213a8df937b10bf714d2472dd75c4edb50220472d97d084b50d0d02c56d1cd017940f14fa53e93531dd15b6f1560f415afbe701210359cf72c727ca59349b370254c2fe30c57f02b5afe1dd2fd36aa7541a5fc088a723ad08006ccb732240b56ff18ada26f209a84081551c70aa1c4b0e00000000000000000000190a000000030b66726f6d6163636f756e7400016e033735320974696d65736d6172740a313535333438363235370001000000b151985c0100
```

**Comment by deathmorlock** [comment]
yes... the last Release https://github.com/magnumripper/JohnTheRipper/releases/tag/1.9.0-Jumbo-1
contains old bitcoin2john.py version. 
I take bitcoin2john.py directly from github source and all works fine.

**Comment by solardiz** [comment]
Thank you for confirming this, @deathmorlock
