### ISSUE TITLE
krb5pa-md5-opencl segfault

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4375]
The krb5pa-md5-opencl segfault first seen in #4368 is also reproducible e.g. on an AWS instance with all very different software versions and a very different NVIDIA GPU. Moreover, running a `john` binary from 2 months ago in there passes this test. Thus, this appear to be our own recent regression, which we need to look into and fix.

```
(gdb) r -te -form=krb5pa-md5-opencl
Starting program: /home/ec2-user/john/run/john -te -form=krb5pa-md5-opencl
Missing separate debuginfos, use: debuginfo-install glibc-2.26-34.amzn2.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe4bca700 (LWP 30239)]
[New Thread 0x7fffe1de1700 (LWP 30240)]
[New Thread 0x7fffe15e0700 (LWP 30241)]
[New Thread 0x7fffe0ddf700 (LWP 30242)]
[New Thread 0x7fffcdfff700 (LWP 30243)]
[New Thread 0x7fffcd7fe700 (LWP 30244)]
Device 1: Tesla V100-SXM2-16GB
Benchmarking: krb5pa-md5-opencl, Kerberos 5 AS-REQ Pre-Auth etype 23 [MD4 HMAC-MD5 RC4 OpenCL/mask accel]... [New Thread 0x7fffccffd700 (LWP 30245)]
[New Thread 0x7fffb7fff700 (LWP 30246)]
[New Thread 0x7fffb77fe700 (LWP 30247)]
[New Thread 0x7fffb6ffd700 (LWP 30248)]
[New Thread 0x7fffb67fc700 (LWP 30249)]
[New Thread 0x7fffb5ffb700 (LWP 30250)]
[New Thread 0x7fffb57fa700 (LWP 30251)]
|
Thread 1 "john" received signal SIGSEGV, Segmentation fault.
0x00007ffff729a438 in clSetKernelArg () from /opt/nvidia/cuda/lib64/libOpenCL.so.1
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.amzn2.0.2.x86_64 gmp-6.0.0-15.amzn2.0.2.x86_64 keyutils-libs-1.5.8-3.amzn2.0.2.x86_64 krb5-libs-1.15.1-37.amzn2.2.2.x86_64 libcom_err-1.42.9-12.amzn2.0.2.x86_64 libcrypt-2.26-34.amzn2.x86_64 libgomp-7.3.1-6.amzn2.0.4.x86_64 libselinux-2.5-12.amzn2.0.2.x86_64 openssl-libs-1.0.2k-19.amzn2.0.3.x86_64 pcre-8.32-17.amzn2.0.2.x86_64 zlib-1.2.7-18.amzn2.x86_64
(gdb) bt
#0  0x00007ffff729a438 in clSetKernelArg () from /opt/nvidia/cuda/lib64/libOpenCL.so.1
#1  0x0000000000752b7b in set_kernel_args () at opencl_krb5pa-md5_fmt_plug.c:155
#2  create_base_clobj () at opencl_krb5pa-md5_fmt_plug.c:222
#3  reset (db=0x4cc5000) at opencl_krb5pa-md5_fmt_plug.c:917
#4  0x0000000000677b4f in benchmark_all () at bench.c:947
#5  0x000000000068ea6c in john_run () at john.c:1795
#6  main (argc=<optimized out>, argv=<optimized out>) at john.c:2206
(gdb) disass $pc
Dump of assembler code for function clSetKernelArg:
   0x00007ffff729a430 <+0>:     test   %rdi,%rdi
   0x00007ffff729a433 <+3>:     je     0x7ffff729a448 <clSetKernelArg+24>
   0x00007ffff729a435 <+5>:     mov    (%rdi),%rax
=> 0x00007ffff729a438 <+8>:     mov    0x130(%rax),%rax
   0x00007ffff729a43f <+15>:    jmpq   *%rax
   0x00007ffff729a441 <+17>:    nopl   0x0(%rax)
   0x00007ffff729a448 <+24>:    mov    $0xffffffd0,%eax
   0x00007ffff729a44d <+29>:    retq   
End of assembler dump.
```

**Comment by solardiz** [comment]
This was also easily reproducible anywhere else I tested. I think this is our fix:

```diff
+++ b/src/opencl_krb5pa-md5_fmt_plug.c
@@ -330,6 +330,7 @@ static void init_kernel(void)
        cl_ulong const_cache_size;
 
        clReleaseKernel(crypt_kernel);
+       crypt_kernel = NULL;
 
        for (i = 0; i < MASK_FMT_INT_PLHDR; i++)
                if (mask_skip_ranges && mask_skip_ranges[i] != -1)
```

**Comment by magnumripper** [comment]
Curiously my debug macros happened to work around that bug while active. There are no easy-fixes-all 😆
