### ISSUE TITLE
Multi-format --fuzz fails with over-read in dyna_salt_cmp() in --enable-asan build

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4962]
```
[solar@super src]$ OMP_NUM_THREADS=3 ../run/john -fuzz
Fuzzing: descrypt, traditional crypt(3) [DES 128/128 AVX]...    Completed
Fuzzing: bsdicrypt, BSDI crypt(3) ("_J9..", 725 iterations) [DES 128/128 AVX]...    Completed
Fuzzing: md5crypt, crypt(3) $1$ (and variants) [MD5 128/128 AVX 4x3]...    Completed
Fuzzing: md5crypt-long, crypt(3) $1$ (and variants) [MD5 32/64]...    Completed
Fuzzing: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]...    Completed
Fuzzing: scrypt (16384, 8, 1) [Salsa20/8 128/128 AVX]... =================================================================
==21675==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x631002cfc8e7 at pc 0x86fbdc bp 0x7ffcb4b01aa0 sp 0x7ffcb4b01a98
READ of size 1 at 0x631002cfc8e7 thread T0
    #0 0x86fbdb in dyna_salt_cmp /home/solar/j/syl/john/src/dyna_salt.c:94
    #1 0x8bbb10 in ldr_load_pw_line /home/solar/j/syl/john/src/loader.c:1051
    #2 0xbbad61 in fuzz_test /home/solar/j/syl/john/src/fuzz.c:585
    #3 0xbbb0e4 in fuzz /home/solar/j/syl/john/src/fuzz.c:687
    #4 0x8ae68d in john_run /home/solar/j/syl/john/src/john.c:1673
    #5 0x8ae68d in main /home/solar/j/syl/john/src/john.c:2083
    #6 0x7f88f8142d1f in __libc_start_main (/lib64/libc.so.6+0x1ed1f)
    #7 0x4069a4 (/home/solar/j/syl/john/run/john+0x4069a4)

0x631002cfc8e7 is located 231 bytes to the right of 65536-byte region [0x631002cec800,0x631002cfc800)
allocated by thread T0 here:
    #0 0x7f88fa0df7ef in malloc (/usr/lib64/libasan.so.1+0x547ef)
    #1 0x8d42c6 in mem_alloc /home/solar/j/syl/john/src/memory.c:86
    #2 0x8d4537 in mem_alloc_tiny /home/solar/j/syl/john/src/memory.c:192
    #3 0x8d4613 in mem_alloc_copy /home/solar/j/syl/john/src/memory.c:219
    #4 0x8bc2e2 in ldr_load_pw_line /home/solar/j/syl/john/src/loader.c:1112
    #5 0xbbad61 in fuzz_test /home/solar/j/syl/john/src/fuzz.c:585
    #6 0xbbb0e4 in fuzz /home/solar/j/syl/john/src/fuzz.c:687
    #7 0x8ae68d in john_run /home/solar/j/syl/john/src/john.c:1673
    #8 0x8ae68d in main /home/solar/j/syl/john/src/john.c:2083
    #9 0x7f88f8142d1f in __libc_start_main (/lib64/libc.so.6+0x1ed1f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/solar/j/syl/john/src/dyna_salt.c:94 dyna_salt_cmp
Shadow bytes around the buggy address:
  0x0c62805978c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c62805978d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c62805978e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c62805978f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c6280597900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c6280597910: fa fa fa fa fa fa fa fa fa fa fa fa[fa]fa fa fa
  0x0c6280597920: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c6280597930: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c6280597940: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c6280597950: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c6280597960: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==21675==ABORTING
```

However, individually it passes:

```
[solar@super src]$ OMP_NUM_THREADS=3 ../run/john -fuzz -form=scrypt
Fuzzing: scrypt (16384, 8, 1) [Salsa20/8 128/128 AVX]...    Completed
All 1 formats passed fuzzing test!
```

Maybe has nothing to do with scrypt or multi-format vs. one-format tests - maybe just luck. Will run more tests. The issue appears to be in dyna_salt_cmp(), which isn't specific to this format.

**Comment by solardiz** [comment]
> Maybe has nothing to do with scrypt or multi-format vs. one-format tests - maybe just luck. Will run more tests. The issue appears to be in dyna_salt_cmp(), which isn't specific to this format.

No, a repeated multi-format fuzz also failed on scrypt in a similar way. So scrypt in a multi-format run is at least a trigger.

**Comment by solardiz** [comment]
Also reproducible with `OMP_NUM_THREADS=1`, also only in multi-format run.

I don't see anything that would cause this in the scrypt format. I suspect it's some general issue in `dyna_salt.c` or maybe `loader.c`.

**Comment by solardiz** [comment]
Certainly nothing to do with scrypt, same crash on AndroidBackup, and after having fuzzed a different format before it.

```
[solar@super src]$ OMP_NUM_THREADS=3 ../run/john -fuzz -form=-scrypt
Fuzzing: descrypt, traditional crypt(3) [DES 128/128 AVX]...    Completed
Fuzzing: bsdicrypt, BSDI crypt(3) ("_J9..", 725 iterations) [DES 128/128 AVX]...    Completed
Fuzzing: md5crypt, crypt(3) $1$ (and variants) [MD5 128/128 AVX 4x3]...    Completed
Fuzzing: md5crypt-long, crypt(3) $1$ (and variants) [MD5 32/64]...    Completed
Fuzzing: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]...    Completed
Fuzzing: LM [DES 128/128 AVX]...    Completed
Fuzzing: AFS, Kerberos AFS [DES 48/64 4K]...    Completed
Fuzzing: tripcode [DES 128/128 AVX]...    Completed
Fuzzing: AndroidBackup [PBKDF2-SHA1 128/128 AVX 4x AES]... =================================================================
==27218==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x63100751880b at pc 0x86fe03 bp 0x7ffe29db1c20 sp 0x7ffe29db1c18
READ of size 1 at 0x63100751880b thread T0
    #0 0x86fe02 in dyna_salt_cmp /home/solar/j/syl/john/src/dyna_salt.c:95
    #1 0x8bbd37 in ldr_load_pw_line /home/solar/j/syl/john/src/loader.c:1051
    #2 0xbbaf88 in fuzz_test /home/solar/j/syl/john/src/fuzz.c:585
    #3 0xbbb30b in fuzz /home/solar/j/syl/john/src/fuzz.c:687
    #4 0x8ae8b4 in john_run /home/solar/j/syl/john/src/john.c:1673
    #5 0x8ae8b4 in main /home/solar/j/syl/john/src/john.c:2083
    #6 0x7f4026e89d1f in __libc_start_main (/lib64/libc.so.6+0x1ed1f)
    #7 0x4069a4 (/home/solar/j/syl/john/run/john+0x4069a4)

0x63100751880b is located 11 bytes to the right of 65536-byte region [0x631007508800,0x631007518800)
allocated by thread T0 here:
    #0 0x7f4028e267ef in malloc (/usr/lib64/libasan.so.1+0x547ef)
    #1 0x8d44ed in mem_alloc /home/solar/j/syl/john/src/memory.c:86
    #2 0x8d475e in mem_alloc_tiny /home/solar/j/syl/john/src/memory.c:192
    #3 0x8d483a in mem_alloc_copy /home/solar/j/syl/john/src/memory.c:219
    #4 0x8bc509 in ldr_load_pw_line /home/solar/j/syl/john/src/loader.c:1112
    #5 0xbbaf88 in fuzz_test /home/solar/j/syl/john/src/fuzz.c:585
    #6 0xbbb30b in fuzz /home/solar/j/syl/john/src/fuzz.c:687
    #7 0x8ae8b4 in john_run /home/solar/j/syl/john/src/john.c:1673
    #8 0x8ae8b4 in main /home/solar/j/syl/john/src/john.c:2083
    #9 0x7f4026e89d1f in __libc_start_main (/lib64/libc.so.6+0x1ed1f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/solar/j/syl/john/src/dyna_salt.c:95 dyna_salt_cmp
Shadow bytes around the buggy address:
  0x0c6280e9b0b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c6280e9b0c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c6280e9b0d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c6280e9b0e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c6280e9b0f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c6280e9b100: fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c6280e9b110: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c6280e9b120: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c6280e9b130: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c6280e9b140: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c6280e9b150: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==27218==ABORTING
```

**Comment by solardiz** [comment]
> 0x631002cfc8e7 is located 231 bytes to the right of 65536-byte region [0x631002cec800,0x631002cfc800)

I think our use of `mem_alloc_tiny` hides this problem in most cases. Perhaps we should force it to `mem_alloc` for testing.

**Comment by solardiz** [comment]
> I think our use of `mem_alloc_tiny` hides this problem in most cases. Perhaps we should force it to `mem_alloc` for testing.

We actually have that logic in `memory.c` when `DEBUG` is defined, but we don't seem to have a `configure` option that would do that?

**Comment by solardiz** [comment]
With `#define DEBUG` patched into `memory.c`, indeed it fails sooner:

```
[solar@super src]$ OMP_NUM_THREADS=3 ../run/john -fuzz
Fuzzing: descrypt, traditional crypt(3) [DES 128/128 AVX]...    Completed
Fuzzing: bsdicrypt, BSDI crypt(3) ("_J9..", 725 iterations) [DES 128/128 AVX]...    Completed
Fuzzing: md5crypt, crypt(3) $1$ (and variants) [MD5 128/128 AVX 4x3]...    Completed
Fuzzing: md5crypt-long, crypt(3) $1$ (and variants) [MD5 32/64]... =================================================================
==31126==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200368d9e4 at pc 0x86fe03 bp 0x7ffe735eec80 sp 0x7ffe735eec78
READ of size 1 at 0x60200368d9e4 thread T0
    #0 0x86fe02 in dyna_salt_cmp /home/solar/j/syl/john/src/dyna_salt.c:95
    #1 0x8bbd37 in ldr_load_pw_line /home/solar/j/syl/john/src/loader.c:1051
    #2 0xbbafe5 in fuzz_test /home/solar/j/syl/john/src/fuzz.c:585
    #3 0xbbb368 in fuzz /home/solar/j/syl/john/src/fuzz.c:687
    #4 0x8ae8b4 in john_run /home/solar/j/syl/john/src/john.c:1673
    #5 0x8ae8b4 in main /home/solar/j/syl/john/src/john.c:2083
    #6 0x7f23d029bd1f in __libc_start_main (/lib64/libc.so.6+0x1ed1f)
    #7 0x4069a4 (/home/solar/j/syl/john/run/john+0x4069a4)

0x60200368d9e4 is located 10 bytes to the right of 10-byte region [0x60200368d9d0,0x60200368d9da)
allocated by thread T0 here:
    #0 0x7f23d22387ef in malloc (/usr/lib64/libasan.so.1+0x547ef)
    #1 0x8d44ed in mem_alloc /home/solar/j/syl/john/src/memory.c:88
    #2 0x8d47a2 in mem_alloc_tiny /home/solar/j/syl/john/src/memory.c:199
    #3 0x8d4870 in mem_alloc_copy /home/solar/j/syl/john/src/memory.c:221
    #4 0x8bbe92 in ldr_load_pw_line /home/solar/j/syl/john/src/loader.c:1062
    #5 0xbbafe5 in fuzz_test /home/solar/j/syl/john/src/fuzz.c:585
    #6 0xbbb368 in fuzz /home/solar/j/syl/john/src/fuzz.c:687
    #7 0x8ae8b4 in john_run /home/solar/j/syl/john/src/john.c:1673
    #8 0x8ae8b4 in main /home/solar/j/syl/john/src/john.c:2083
    #9 0x7f23d029bd1f in __libc_start_main (/lib64/libc.so.6+0x1ed1f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/solar/j/syl/john/src/dyna_salt.c:95 dyna_salt_cmp
Shadow bytes around the buggy address:
  0x0c04806c9ae0: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c04806c9af0: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c04806c9b00: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c04806c9b10: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c04806c9b20: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
=>0x0c04806c9b30: fa fa 00 00 fa fa 00 00 fa fa 00 02[fa]fa 00 00
  0x0c04806c9b40: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c04806c9b50: fa fa 00 00 fa fa 00 02 fa fa 00 00 fa fa 00 00
  0x0c04806c9b60: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c04806c9b70: fa fa 00 02 fa fa 00 00 fa fa 00 00 fa fa 00 00
  0x0c04806c9b80: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 02
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==31126==ABORTING
```

**Comment by solardiz** [comment]
My current understanding is it's a design bug in our fuzzer: `fuzz_test()` forcibly updates `db->format` for each new format fuzzed, but I don't see it otherwise reset the db anywhere. So different-format hashes accumulate in the db - something the logic in our loader doesn't support. Normally, once a format is set, the loader sticks to just that one format.

**Comment by solardiz** [comment]
I think this is the fix, although my `--fuzz` is still running (and probably will be for hours more):

```diff
+++ b/src/fuzz.c
@@ -32,6 +32,7 @@
 #include "misc.h"      // error()
 #include "config.h"
 #include "john.h"
+#include "options.h"
 #include "params.h"
 #include "signals.h"
 #include "unicode.h"
@@ -575,13 +576,13 @@ static void fuzz_test(struct db_main *db, struct fmt_main *format)
        current = format->params.tests;
 
        init_status(format->params.label);
+       ldr_init_database(db, &options.loader);
        db->format = format;

        while (1) {
                ret = get_next_fuzz_case(format->params.label, current->ciphertext);
                save_index(index++);
                line = fuzz_hash;
-               db->format = format;
                ldr_load_pw_line(db, line);

                if (!ret) {
+++ b/src/john.c
@@ -1669,7 +1669,6 @@ static void john_run(void)
                options.loader.flags |= DB_WORDS;
                list_init(&single_seed); /* Required for DB_WORDS */

-               ldr_init_database(&database, &options.loader);
                exit_status = fuzz(&database);
        }
 #endif
```
