### ISSUE TITLE
as400-ssha1 fails --fuzz in --enable-asan build

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4966]
With #4962 fixed:

```
[solar@super src]$ OMP_NUM_THREADS=3 time ../run/john -fuzz
Fuzzing: descrypt, traditional crypt(3) [DES 128/128 AVX]...    Completed
Fuzzing: bsdicrypt, BSDI crypt(3) ("_J9..", 725 iterations) [DES 128/128 AVX]...    Completed
Fuzzing: md5crypt, crypt(3) $1$ (and variants) [MD5 128/128 AVX 4x3]...    Completed
Fuzzing: md5crypt-long, crypt(3) $1$ (and variants) [MD5 32/64]...    Completed
Fuzzing: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]...    Completed
Fuzzing: scrypt (16384, 8, 1) [Salsa20/8 128/128 AVX]...    Completed
Fuzzing: LM [DES 128/128 AVX]...    Completed
Fuzzing: AFS, Kerberos AFS [DES 48/64 4K]...    Completed
Fuzzing: tripcode [DES 128/128 AVX]...    Completed
Fuzzing: AndroidBackup [PBKDF2-SHA1 128/128 AVX 4x AES]...    Completed
Fuzzing: adxcrypt, IBM/Toshiba 4690 [ADXCRYPT 32/64]... Note: This format may emit false positives, so it will keep trying even after finding a possible candidate.
   Completed
Fuzzing: agilekeychain, 1Password Agile Keychain [PBKDF2-SHA1 AES 128/128 AVX 4x]... Note: This format may emit false positives, so it will keep trying even after finding a possible candidate.
   Completed
Fuzzing: aix-ssha1, AIX LPA {ssha1} [PBKDF2-SHA1 128/128 AVX 4x]...    Completed
Fuzzing: aix-ssha256, AIX LPA {ssha256} [PBKDF2-SHA256 128/128 AVX 4x]...    Completed
Fuzzing: aix-ssha512, AIX LPA {ssha512} [PBKDF2-SHA512 128/128 AVX 2x]...    Completed
Fuzzing: andOTP [SHA256 32/64]...    Completed
Fuzzing: ansible, Ansible Vault [PBKDF2-SHA256 HMAC-256 128/128 AVX 4x]...    Completed
Fuzzing: argon2 [Blake2 AVX]...    Completed
Fuzzing: as400-des, AS/400 DES [DES 32/64]...    Completed
Fuzzing: as400-ssha1, AS400-SaltedSHA1 [?] in UTF-8 mode... ASAN:SIGSEGV
=================================================================
==31274==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f2dac7f89df sp 0x7fffacbdf4f8 bp 0x7fffacbdfd60 T0)
    #0 0x7f2dac7f89de in __strlen_sse42 (/lib64/libc.so.6+0x1339de)
    #1 0x7f2dae65af46 in __interceptor_strcpy (/usr/lib64/libasan.so.1+0x2ef46)
    #2 0x66ef65 in Convert /home/solar/j/syl/john/src/as400_ssha1_fmt_plug.c:105
    #3 0x66f729 in our_valid /home/solar/j/syl/john/src/as400_ssha1_fmt_plug.c:161
    #4 0x8b8e86 in ldr_split_line /home/solar/j/syl/john/src/loader.c:664
    #5 0x8bb077 in ldr_load_pw_line /home/solar/j/syl/john/src/loader.c:958
    #6 0xbbadb5 in fuzz_test /home/solar/j/syl/john/src/fuzz.c:586
    #7 0xbbb131 in fuzz /home/solar/j/syl/john/src/fuzz.c:688
    #8 0x8ae67c in john_run /home/solar/j/syl/john/src/john.c:1672
    #9 0x8ae67c in main /home/solar/j/syl/john/src/john.c:2082
    #10 0x7f2dac6e3d1f in __libc_start_main (/lib64/libc.so.6+0x1ed1f)
    #11 0x4069a4 (/home/solar/j/syl/john/run/john+0x4069a4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 __strlen_sse42
==31274==ABORTING
17861.23user 193.04system 5:01:02elapsed 99%CPU (0avgtext+0avgdata 94621328maxresident)k
1240inputs+629656outputs (4major+27314910minor)pagefaults 0swaps
```

Yes, took 5 hours to get there. With `andOTP` skipped, it takes 1 hour:

```
[solar@super src]$ OMP_NUM_THREADS=1 time ../run/john -fuzz -format=-andotp
Fuzzing: descrypt, traditional crypt(3) [DES 128/128 AVX]...    Completed
Fuzzing: bsdicrypt, BSDI crypt(3) ("_J9..", 725 iterations) [DES 128/128 AVX]...    Completed
Fuzzing: md5crypt, crypt(3) $1$ (and variants) [MD5 128/128 AVX 4x3]...    Completed
Fuzzing: md5crypt-long, crypt(3) $1$ (and variants) [MD5 32/64]...    Completed
Fuzzing: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]...    Completed
Fuzzing: scrypt (16384, 8, 1) [Salsa20/8 128/128 AVX]...    Completed
Fuzzing: LM [DES 128/128 AVX]...    Completed
Fuzzing: AFS, Kerberos AFS [DES 48/64 4K]...    Completed
Fuzzing: tripcode [DES 128/128 AVX]...    Completed
Fuzzing: AndroidBackup [PBKDF2-SHA1 128/128 AVX 4x AES]...    Completed
Fuzzing: adxcrypt, IBM/Toshiba 4690 [ADXCRYPT 32/64]... Note: This format may emit false positives, so it will keep trying even after finding a possible candidate.
   Completed
Fuzzing: agilekeychain, 1Password Agile Keychain [PBKDF2-SHA1 AES 128/128 AVX 4x]... Note: This format may emit false positives, so it will keep trying even after finding a possible candidate.
   Completed
Fuzzing: aix-ssha1, AIX LPA {ssha1} [PBKDF2-SHA1 128/128 AVX 4x]...    Completed
Fuzzing: aix-ssha256, AIX LPA {ssha256} [PBKDF2-SHA256 128/128 AVX 4x]...    Completed
Fuzzing: aix-ssha512, AIX LPA {ssha512} [PBKDF2-SHA512 128/128 AVX 2x]...    Completed
Fuzzing: ansible, Ansible Vault [PBKDF2-SHA256 HMAC-256 128/128 AVX 4x]...    Completed
Fuzzing: argon2 [Blake2 AVX]...    Completed
Fuzzing: as400-des, AS/400 DES [DES 32/64]...    Completed
Fuzzing: as400-ssha1, AS400-SaltedSHA1 [?] in UTF-8 mode... ASAN:SIGSEGV
=================================================================
==5068==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f6b8348f9df sp 0x7ffed4754298 bp 0x7ffed4754b00 T0)
    #0 0x7f6b8348f9de in __strlen_sse42 (/lib64/libc.so.6+0x1339de)
    #1 0x7f6b852f1f46 in __interceptor_strcpy (/usr/lib64/libasan.so.1+0x2ef46)
    #2 0x66ef65 in Convert /home/solar/j/syl/john/src/as400_ssha1_fmt_plug.c:105
    #3 0x66f729 in our_valid /home/solar/j/syl/john/src/as400_ssha1_fmt_plug.c:161
    #4 0x8b8e86 in ldr_split_line /home/solar/j/syl/john/src/loader.c:664
    #5 0x8bb077 in ldr_load_pw_line /home/solar/j/syl/john/src/loader.c:958
    #6 0xbbadb5 in fuzz_test /home/solar/j/syl/john/src/fuzz.c:586
    #7 0xbbb131 in fuzz /home/solar/j/syl/john/src/fuzz.c:688
    #8 0x8ae67c in john_run /home/solar/j/syl/john/src/john.c:1672
    #9 0x8ae67c in main /home/solar/j/syl/john/src/john.c:2082
    #10 0x7f6b8337ad1f in __libc_start_main (/lib64/libc.so.6+0x1ed1f)
    #11 0x4069a4 (/home/solar/j/syl/john/run/john+0x4069a4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 __strlen_sse42
==5068==ABORTING
3371.10user 127.11system 58:23.89elapsed 99%CPU (0avgtext+0avgdata 52538752maxresident)k
0inputs+580432outputs (0major+16195591minor)pagefaults 0swaps
```

Luckily, it also crashes instantly when fuzzed individually:

```
[solar@super src]$ OMP_NUM_THREADS=1 time ../run/john -fuzz -format=as400-ssha1
Fuzzing: as400-ssha1, AS400-SaltedSHA1 [?] in UTF-8 mode... ASAN:SIGSEGV
=================================================================
==5225==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fcb581489df sp 0x7ffe32d67da8 bp 0x7ffe32d68610 T0)
    #0 0x7fcb581489de in __strlen_sse42 (/lib64/libc.so.6+0x1339de)
    #1 0x7fcb59faaf46 in __interceptor_strcpy (/usr/lib64/libasan.so.1+0x2ef46)
    #2 0x66ef65 in Convert /home/solar/j/syl/john/src/as400_ssha1_fmt_plug.c:105
    #3 0x66f729 in our_valid /home/solar/j/syl/john/src/as400_ssha1_fmt_plug.c:161
    #4 0x8b8e86 in ldr_split_line /home/solar/j/syl/john/src/loader.c:664
    #5 0x8bb077 in ldr_load_pw_line /home/solar/j/syl/john/src/loader.c:958
    #6 0xbbadb5 in fuzz_test /home/solar/j/syl/john/src/fuzz.c:586
    #7 0xbbb131 in fuzz /home/solar/j/syl/john/src/fuzz.c:688
    #8 0x8ae67c in john_run /home/solar/j/syl/john/src/john.c:1672
    #9 0x8ae67c in main /home/solar/j/syl/john/src/john.c:2082
    #10 0x7fcb58033d1f in __libc_start_main (/lib64/libc.so.6+0x1ed1f)
    #11 0x4069a4 (/home/solar/j/syl/john/run/john+0x4069a4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 __strlen_sse42
==5225==ABORTING
0.57user 0.15system 0:00.74elapsed 98%CPU (0avgtext+0avgdata 462596maxresident)k
0inputs+16outputs (0major+62962minor)pagefaults 0swaps
```

**Comment by solardiz** [comment]
Fix:

```diff
+++ b/src/as400_ssha1_fmt_plug.c
@@ -143,9 +143,11 @@ static int our_valid(char *ciphertext, struct fmt_main *self)
 
        if (strncmp(ciphertext, FORMAT_TAG, FORMAT_TAG_LEN))
                return 0;
-       if (hexlenu(&ciphertext[FORMAT_TAG_LEN], 0) != BINARY_SIZE*2)
+       if (hexlenu(&ciphertext[FORMAT_TAG_LEN], 0) != BINARY_SIZE * 2)
                return 0;
-       if (strlen(&ciphertext[FORMAT_TAG_LEN+2*BINARY_SIZE]) > 10)
+       if (ciphertext[FORMAT_TAG_LEN + 2 * BINARY_SIZE] != '$')
+               return 0;
+       if (strlen(&ciphertext[FORMAT_TAG_LEN + 2 * BINARY_SIZE + 1]) > 10)
                return 0;
        if (options.input_enc == UTF_8 && !valid_utf8((UTF8*)ciphertext)) {
                static int error_shown = 0;
```

This also allows for salts of length 10, which looks like how this was intended. Previously, the code would wrongly(?) limit to 9 (counting the `$` against the salt length limit).
