### ISSUE TITLE
BestCrypt fails --fuzz in --enable-asan build

### ISSUE THREAD

**Issue by solardiz** [openwall/john#4967]
```
[solar@super src]$ OMP_NUM_THREADS=3 time ../run/john -fuzz -format=-md5crypt-long,-scrypt,-andOTP,-argon2,-as400-ssha1,-agilekeychain,-axcrypt,-AndroidBackup
Fuzzing: descrypt, traditional crypt(3) [DES 128/128 AVX]...    Completed
Fuzzing: bsdicrypt, BSDI crypt(3) ("_J9..", 725 iterations) [DES 128/128 AVX]...    Completed
Fuzzing: md5crypt, crypt(3) $1$ (and variants) [MD5 128/128 AVX 4x3]...    Completed
Fuzzing: bcrypt ("$2a$05", 32 iterations) [Blowfish 32/64 X3]...    Completed
Fuzzing: LM [DES 128/128 AVX]...    Completed
Fuzzing: AFS, Kerberos AFS [DES 48/64 4K]...    Completed
Fuzzing: tripcode [DES 128/128 AVX]...    Completed
Fuzzing: adxcrypt, IBM/Toshiba 4690 [ADXCRYPT 32/64]... Note: This format may emit false positives, so it will keep trying even after finding a possible candidate.
   Completed
Fuzzing: aix-ssha1, AIX LPA {ssha1} [PBKDF2-SHA1 128/128 AVX 4x]...    Completed
Fuzzing: aix-ssha256, AIX LPA {ssha256} [PBKDF2-SHA256 128/128 AVX 4x]...    Completed
Fuzzing: aix-ssha512, AIX LPA {ssha512} [PBKDF2-SHA512 128/128 AVX 2x]...    Completed
Fuzzing: ansible, Ansible Vault [PBKDF2-SHA256 HMAC-256 128/128 AVX 4x]...    Completed
Fuzzing: as400-des, AS/400 DES [DES 32/64]...    Completed
Fuzzing: asa-md5, Cisco ASA [?]...    Completed
Fuzzing: AzureAD [PBKDF2-SHA256 128/128 AVX 4x] in UTF-8 mode...    Completed
Fuzzing: BestCrypt, Jetico BestCrypt (.jbc) (SHA-256 + AES XTS mode) [PKCS#12 PBE (SHA1/SHA2) 32/64]... =================================================================
==5272==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c0017a9fb3 at pc 0x6768e8 bp 0x7ffd004690d0 sp 0x7ffd004690c8
READ of size 1 at 0x60c0017a9fb3 thread T0
    #0 0x6768e7 in get_salt /home/solar/j/syl/john/src/bestcrypt_fmt_plug.c:266
    #1 0x8bba37 in ldr_load_pw_line /home/solar/j/syl/john/src/loader.c:1045
    #2 0xbbadb5 in fuzz_test /home/solar/j/syl/john/src/fuzz.c:586
    #3 0xbbb131 in fuzz /home/solar/j/syl/john/src/fuzz.c:688
    #4 0x8ae67c in john_run /home/solar/j/syl/john/src/john.c:1672
    #5 0x8ae67c in main /home/solar/j/syl/john/src/john.c:2082
    #6 0x7efc0af40d1f in __libc_start_main (/lib64/libc.so.6+0x1ed1f)
    #7 0x4069a4 (/home/solar/j/syl/john/run/john+0x4069a4)

0x60c0017a9fb3 is located 0 bytes to the right of 115-byte region [0x60c0017a9f40,0x60c0017a9fb3)
allocated by thread T0 here:
    #0 0x7efc0cedd7ef in malloc (/usr/lib64/libasan.so.1+0x547ef)
    #1 0x7efc0afa2f41 in strdup (/lib64/libc.so.6+0x80f41)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/solar/j/syl/john/src/bestcrypt_fmt_plug.c:266 get_salt
Shadow bytes around the buggy address:
  0x0c18802ed3a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c18802ed3b0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c18802ed3c0: 00 00 00 00 00 00 06 fa fa fa fa fa fa fa fa fa
  0x0c18802ed3d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 07 fa
  0x0c18802ed3e0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
=>0x0c18802ed3f0: 00 00 00 00 00 00[03]fa fa fa fa fa fa fa fa fa
  0x0c18802ed400: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 06 fa
  0x0c18802ed410: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c18802ed420: 00 00 00 00 00 00 07 fa fa fa fa fa fa fa fa fa
  0x0c18802ed430: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa
  0x0c18802ed440: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==5272==ABORTING
145.86user 14.31system 2:40.29elapsed 99%CPU (0avgtext+0avgdata 2950388maxresident)k
0inputs+101440outputs (0major+347805minor)pagefaults 0swaps
```

```
[solar@super src]$ OMP_NUM_THREADS=1 time ../run/john -fuzz -form=BestCrypt
Fuzzing: BestCrypt, Jetico BestCrypt (.jbc) (SHA-256 + AES XTS mode) [PKCS#12 PBE (SHA1/SHA2) 32/64]... =================================================================
==5357==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c000066a73 at pc 0x676926 bp 0x7fff4699aa00 sp 0x7fff4699a9f8
READ of size 1 at 0x60c000066a73 thread T0
    #0 0x676925 in get_salt /home/solar/j/syl/john/src/bestcrypt_fmt_plug.c:266
    #1 0x8bba75 in ldr_load_pw_line /home/solar/j/syl/john/src/loader.c:1045
    #2 0xbbadf3 in fuzz_test /home/solar/j/syl/john/src/fuzz.c:586
    #3 0xbbb16f in fuzz /home/solar/j/syl/john/src/fuzz.c:688
    #4 0x8ae6ba in john_run /home/solar/j/syl/john/src/john.c:1672
    #5 0x8ae6ba in main /home/solar/j/syl/john/src/john.c:2082
    #6 0x7fb597a6ad1f in __libc_start_main (/lib64/libc.so.6+0x1ed1f)
    #7 0x4069a4 (/home/solar/j/syl/john/run/john+0x4069a4)

0x60c000066a73 is located 0 bytes to the right of 115-byte region [0x60c000066a00,0x60c000066a73)
allocated by thread T0 here:
    #0 0x7fb599a077ef in malloc (/usr/lib64/libasan.so.1+0x547ef)
    #1 0x7fb597accf41 in strdup (/lib64/libc.so.6+0x80f41)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/solar/j/syl/john/src/bestcrypt_fmt_plug.c:266 get_salt
Shadow bytes around the buggy address:
  0x0c1880004cf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1880004d00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1880004d10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1880004d20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1880004d30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c1880004d40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00[03]fa
  0x0c1880004d50: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c1880004d60: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
  0x0c1880004d70: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa
  0x0c1880004d80: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c1880004d90: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==5357==ABORTING
2.41user 0.45system 0:02.87elapsed 99%CPU (0avgtext+0avgdata 357280maxresident)k
0inputs+1848outputs (0major+95347minor)pagefaults 0swaps
```

**Comment by solardiz** [comment]
Fix:

```diff
+++ b/src/bestcrypt_fmt_plug.c
@@ -257,12 +257,12 @@ static void *get_salt(char *ciphertext)
        p = strtokm(NULL, "$");
        cs.salt_size = atoi(p);
        p = strtokm(NULL, "$");
-       for (i = 0; i < cs.salt_size; i++)
+       for (i = 0; i < cs.salt_size && p[2*i]; i++)
                cs.salt[i] = (atoi16[ARCH_INDEX(p[2*i])] << 4) | atoi16[ARCH_INDEX(p[2*i+1])];
        p = strtokm(NULL, "$");
        cs.active_slots = atoi(p);
        p = strtokm(NULL, "$");
-       for (i = 0; i < cs.active_slots * kKeySlotSize; i++)
+       for (i = 0; i < cs.active_slots * kKeySlotSize && p[2*i]; i++)
                cs.key[i] = (atoi16[ARCH_INDEX(p[2*i])] << 4) | atoi16[ARCH_INDEX(p[2*i+1])];
 
        MEM_FREE(keeptr);
```
