### ISSUE TITLE
Crash when parsing malformed recovery file

### ISSUE THREAD

**Issue by retpoline** [openwall/john#4985]
Hello there!

Here's some details on the crash when processing a malformed REC file.

**Build Info**

```
OS: Ubuntu Linux 20.04 x86_64

$ ./john --list=build-info
Version: 1.9.0-jumbo-1+bleeding-4cf9ab5f5 2021-12-27 20:39:11 +0100
Build: linux-gnu 64-bit x86_64 AVX2 AC OMP
SIMD: AVX2, interleaving: MD4:3 MD5:3 SHA1:1 SHA256:1 SHA512:1
CPU tests: AVX2
$JOHN is ./
Format interface version: 14
Max. number of reported tunable costs: 4
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
SINGLE_IDX_MAX: 32768
SINGLE_BUF_MAX: 4294967295
Effective limit: Max. KPC 32768
Max. Markov mode level: 400
Max. Markov mode password length: 30
gcc version: 9.3.0
GNU libc version: 2.31 (loaded: 2.31)
Crypto library: OpenSSL
OpenSSL library version: 01010106f
OpenSSL 1.1.1f  31 Mar 2020
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
times(2) sysconf(_SC_CLK_TCK) is 100
Using times(2) for timers, resolution 10 ms
HR timer: clock_gettime(), latency 40 ns
Total physical host memory: 7954 MiB
Available physical host memory: 7039 MiB
Terminal locale string: en_US.UTF-8
Parsed terminal locale: UTF-8
```

**Repro**

```
$ cat john.rec
REC4
8195068000000
```

**Debug**
```
$ ./john --restore
Incorrect crash recovery file: john.rec

$ LD_PRELOAD=/usr/lib/libefence.so ./john --restore

  Electric Fence 2.2 Copyright (C) 1987-1999 Bruce Perens <bruce@perens.com>

ElectricFence Exiting: mmap() failed: Segmentation fault (core dumped)

$ gdb -q john
Reading symbols from john...
(gdb) set environment LD_PRELOAD /usr/lib/libefence.so
(gdb) r --restore
Starting program: /home/user/soft/john/run/john --restore

  Electric Fence 2.2 Copyright (C) 1987-1999 Bruce Perens <bruce@perens.com>
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

  Electric Fence 2.2 Copyright (C) 1987-1999 Bruce Perens <bruce@perens.com>

ElectricFence Exiting: mmap() failed: 
Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff7dc462f in EF_Printv () from /usr/lib/libefence.so
#2  0x00007ffff7dc4845 in EF_Exitv () from /usr/lib/libefence.so
#3  0x00007ffff7dc48f9 in EF_Exit () from /usr/lib/libefence.so
#4  0x00007ffff7dc4226 in Page_Create () from /usr/lib/libefence.so
#5  0x00007ffff7dc380c in ?? () from /usr/lib/libefence.so
#6  0x00007ffff7dc3e7e in memalign () from /usr/lib/libefence.so
#7  0x00005555558ae1ea in mem_alloc (size=size@entry=2163193871) at memory.c:90
#8  0x00005555558ae3f3 in mem_alloc_tiny (size=2163193864, align=<optimized out>, align@entry=8) at memory.c:201
#9  0x00005555558b7786 in rec_restore_args (lock=lock@entry=1) at recovery.c:557
#10 0x00005555558b54cb in opt_init (name=<optimized out>, argc=2, argv=0x7fffffffe438) at options.c:601
#11 0x0000555555899277 in john_init (argv=0x7fffffffe438, argc=2, name=<optimized out>) at john.c:1527
#12 main (argc=2, argv=0x7fffffffe438) at john.c:2065

(gdb) i r
rax            0x7fffffffdb38      140737488345912
rbx            0x0                 0
rcx            0x0                 0
rdx            0x0                 0
rsi            0x73                115
rdi            0x0                 0
rbp            0x7fffffffdaa6      0x7fffffffdaa6
rsp            0x7fffffffda98      0x7fffffffda98
r8             0x7ffff78bd660      140737346524768
r9             0x0                 0
r10            0x7ffff7dc2a50      140737351789136
r11            0x7ffff785b660      140737346123360
r12            0x7fffffffdaa7      140737488345767
r13            0x7ffff7dc4c60      140737351797856
r14            0x7fffffffdb10      140737488345872
r15            0x7ffff7dc4bc0      140737351797696
rip            0x7ffff785b675      0x7ffff785b675 <__strlen_avx2+21>
eflags         0x10283             [ CF SF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0

(gdb) x/i $rip
=> 0x7ffff785b675 <__strlen_avx2+21>:	vpcmpeqb (%rdi),%ymm0,%ymm1
(gdb) 
```

Thanks for your time.

**Comment by solardiz** [comment]
@retpoline Are you fuzzing? In a VM? With very limited RAM per process? My guess is you actually triggered an out-of-memory condition that your system's own libraries failed to handle well.

However, with just slightly different input you'd trigger misbehavior in JtR, and perhaps we shouldn't allow allocations this large in there. So we'll need to fix the code in JtR. Thanks.

**Comment by retpoline** [comment]
Hi @solardiz,

Yes, it was found fuzzing with [litefuzz](https://github.com/sec-tools/litefuzz) in a VM with 8gb ram, but no further process memory restrictions other than what is default on Ubuntu 20.04.

Ah, this test case was minimized a bit as the original crasher had different values.

```
REC4
666666666666666/5816/fuzz_jthykaqh.zz
--format=crypt
1
0
0
0
0
0
0
0
0
0
1
0
0
0
```

Makes sense. Thanks for having a look!

**Comment by solardiz** [comment]
@retpoline Once we fix this, you might want to build with `./configure --enable-asan` for further fuzzing of our project. That will likely uncover more issues. Thanks.

**Comment by magnumripper** [comment]
I just added the "fuzz bug" label and only then saw the derogatory description it currently has. No offense meant.

**Comment by solardiz** [comment]
@magnumripper I've just updated the description. With that, I'm also going to set this label on more issues.

**Comment by solardiz** [comment]
I intend to fix this by simply rejecting unreasonably high values of `argc`:

```diff
+++ b/src/options.c
@@ -418,6 +418,10 @@ void opt_init(char *name, int argc, char **argv)
                        printf("Use --help to list all available options.\n");
                }
                exit(0);
+       } else if (argc > 10000000 && !rec_restored) {
+               if (john_main_process)
+                       fprintf(stderr, "Too many command-line arguments\n");
+               error();
        }
 
        /*
diff --git a/src/recovery.c b/src/recovery.c
index 60aab62..abaefcd 100644
--- a/src/recovery.c
+++ b/src/recovery.c
@@ -552,7 +552,7 @@ void rec_restore_args(int lock)
 
        if (fscanf(rec_file, "%d\n", &argc) != 1)
                rec_format_error("fscanf");
-       if (argc < 2)
+       if (argc < 2 || argc > 11000000)
                rec_format_error(NULL);
        argv = mem_alloc_tiny(sizeof(char *) * (argc + 1), MEM_ALIGN_WORD);
 
```

This doesn't fully validate the parsing of the integer, but that's consistent with how we don't currently validate the rest of them. We only make sure the integer values are in range and consistent, not that the original strings are proper integers. We might want to make the parsing more robust in that respect separately, not as part of fixing this issue.

**Comment by solardiz** [comment]
Here's an idea I'd like to have recorded in here, but don't intend to implement: for rewriting, we could `fseek()` the `.rec` file to offset right after all of the command-line arguments, not to start of file, and rewrite only the tiny portion that is expected to change. This would probably increase reliability and provide some speedup when running with lots of command-line arguments. Unfortunately, this idea is incompatible with us stopping to rewrite the file in place (and instead writing a new file and renaming), which is an even safer approach. As another drawback, this would be more likely to trigger stdio implementation bugs on weird systems.
