### ISSUE TITLE
crash in opencl formats with gpu-side mask when in ASan build

### ISSUE THREAD

**Issue by AlekseyCherepanov** [openwall/john#5022]
john is fresh:
```
$ ../run/john
John the Ripper 1.9.0-jumbo-1+bleeding-b81ef254b 2022-01-24 23:51:52 +0100 ASan [linux-gnu 64-bit x86_64 AVX2 AC]
```

It was built with asan:
```
$ ./configure --enable-asan --disable-openmp
```

The crash:
```
$ ../run/john --test --format=nt-opencl
NOTE: This is a debug build, speed will be lower than normal
Device 1: Hawaii [AMD Radeon (TM) R9 390 Series]
Benchmarking: NT-opencl [MD4 OpenCL/mask accel]... Build log: /tmp/OCL137294T1.cl:332:18: warning: unknown attribute 'max_constant_size' ignored
                __attribute__((max_constant_size (NUM_INT_KEYS * 4)))
                               ^
1 warning generated.

=================================================================
==137294==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55c837144355 at pc 0x55c8353d579f bp 0x7ffe09d61fb0 sp 0x7ffe09d61fa8
READ of size 1 at 0x55c837144355 thread T0
    #0 0x55c8353d579e in finalize_mask /home/user/john/src/mask.c:2459
    #1 0x55c8353d6eca in mask_init /home/user/john/src/mask.c:2312
    #2 0x55c835382048 in benchmark_all /home/user/john/src/bench.c:894
    #3 0x55c8353b45f0 in john_run /home/user/john/src/john.c:1661
    #4 0x55c8353b45f0 in main /home/user/john/src/john.c:2082
    #5 0x7f77e4bbdd09 in __libc_start_main ../csu/libc-start.c:308
    #6 0x55c834eb6469 in _start (/home/user/john/run/john+0x2d8469)

0x55c837144355 is located 11 bytes to the left of global variable 'cpu_mask_ctx' defined in 'mask.c:42:25' (0x55c837144360) of size 34288
0x55c837144355 is located 37 bytes to the right of global variable 'rec_ctx' defined in 'mask.c:42:39' (0x55c83713bd40) of size 34288
SUMMARY: AddressSanitizer: global-buffer-overflow /home/user/john/src/mask.c:2459 in finalize_mask
Shadow bytes around the buggy address:
  0x0ab986e20810: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ab986e20820: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ab986e20830: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ab986e20840: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ab986e20850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ab986e20860: 00 00 00 00 00 00 f9 f9 f9 f9[f9]f9 00 00 00 00
  0x0ab986e20870: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ab986e20880: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ab986e20890: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ab986e208a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ab986e208b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==137294==ABORTING
```

I tried `raw-sha1-opencl`: it crashes too with `--test`. Real attack with `--mask` and `nt-opencl` crashes similarly.

Real attack with `--mask` and `odf-opencl` does not crash. Hence the assumption that it affects only formats with gpu-side mask.

**Comment by solardiz** [comment]
> READ of size 1

This being a read rather than write is probably why we didn't catch this in non-ASan builds.

**Comment by AlekseyCherepanov** [comment]
The fix works. Thanks!
