### ISSUE TITLE
segfault with extra big value for `--mask-internal-target=`

### ISSUE THREAD

**Issue by AlekseyCherepanov** [openwall/john#5115]
Playing with options after #5084, I tried values like `255 * 255 * 255 * x` for `--mask-internal-target=`. Overly big `x` causes message like the following:
```
0: OpenCL CL_INVALID_BUFFER_SIZE (-61) error in opencl_DES_bs_plug.c:933 - Create buffer_int_des_keys failed.
```

But smaller values cause crashes (at least under ASan) because lws/gws become 0. Crash is not immediate, it takes a few minutes.

`x` is 32:
```
$ cat t.pw
AAQg8DP4VZOHs

$ ./john/run/john t.pw --format=descrypt-opencl --mask='[\x01-\xff][\x01-\xff][\x01-\xff][\x01-\x21]?a?a?a' --lws=1 --gws=1 --mask-internal-target=530604000
Device 1: Hawaii [AMD Radeon (TM) R9 390 Series]
Using default input encoding: UTF-8
Loaded 1 password hash (descrypt-opencl, traditional crypt(3) [DES OpenCL])
Build log: /tmp/OCL7555T2.cl:208:23: warning: unknown attribute 'max_constant_size' ignored
                                   __attribute__((max_constant_size((ACTIVE_PLACEHOLDER * 32 * ITER_COUNT))))
                                                  ^
1 warning generated.

LWS=0 GWS=0 x547185375
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status

Message from syslogd@h at Apr 21 21:05:33 ...
 kernel:[  963.742006] EXT4-fs (sda1): failed to convert unwritten extents to written extents -- potential data loss!  (inode 3544455, error -30)
AddressSanitizer:DEADLYSIGNAL
=================================================================
==7555==ERROR: AddressSanitizer: SEGV on unknown address (pc 0x564305b5dd49 bp 0x7ffee17b1390 sp 0x7ffee17b1370 T0)
==7555==The signal is caused by a READ memory access.
==7555==Hint: this fault was caused by a dereference of a high value address (see register values below).  Dissassemble the provided pc to learn which register was used.
    #0 0x564305b5dd49 in get_key_mm /home/user/john/src/opencl_DES_bs_plug.c:1127
    #1 0x564305a5939e in crk_get_key2 /home/user/john/src/cracker.c:1331
    #2 0x564305abc381 in status_print_cracking /home/user/john/src/status.c:284
    #3 0x564305abd6fd in status_print /home/user/john/src/status.c:473
    #4 0x564305a535e1 in crk_process_event /home/user/john/src/cracker.c:809
    #5 0x564305a55a23 in crk_password_loop /home/user/john/src/cracker.c:852
    #6 0x564305a57f08 in crk_salt_loop /home/user/john/src/cracker.c:1080
    #7 0x564305a586da in process_key /home/user/john/src/cracker.c:1187
    #8 0x564305a942d7 in generate_keys /home/user/john/src/mask.c:1670
    #9 0x564305a9912b in do_mask_crack /home/user/john/src/mask.c:2704
    #10 0x564305a7660c in john_run /home/user/john/src/john.c:1835
    #11 0x564305a7660c in main /home/user/john/src/john.c:2082
    #12 0x7ff7869ebd09 in __libc_start_main ../csu/libc-start.c:308
    #13 0x564305573469 in _start (/home/user/john/run/john+0x2db469)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/user/john/src/opencl_DES_bs_plug.c:1127 in get_key_mm
==7555==ABORTING
```

There is a message from syslogd about file system. I am not sure if it is related to the problem or just a result of previous multiple reboots using reset button due to hang ups.

It happens under opencl from AMDGPU-PRO. My gpu is AMD R9 390 with 8gb of memory.

`x = 31` works for me. It hangs for 7 minutes: `^C` cannot exit john immediately and parallel clinfo waits end of batch too, but things work then.

`x = 40` causes `LWS=0` too. So there is some room before `CL_INVALID_BUFFER_SIZE`.

**Comment by AlekseyCherepanov** [comment]
Oops, `\x01-\x21` means `x = 33`. Specified `530604000` is `255 * 255 * 255 * 32`. But john upgraded value to `x547185375`, that's `255 * 255 * 255 * 33`.

**Comment by AlekseyCherepanov** [comment]
Excerpts from `clinfo`:
```
$ clinfo

  Platform Version                                OpenCL 2.1 AMD-APP (3180.7)

  Device Name                                     Hawaii

  Device Version                                  OpenCL 1.2 AMD-APP (3180.7)

  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             256
  Preferred work group size (AMD)                 256
  Max work group size (AMD)                       1024

  Global memory size                              8527360000 (7.942GiB)
  Global free memory (AMD)                        8307908 (7.923GiB) 6285372 (5.994GiB)

  Max memory allocation                           4244635648 (3.953GiB)

  Max constant buffer size                        4244635648 (3.953GiB)
```

Interestingly `clinfo` reports only free memory as `Global memory size`. So it is possible to check memory usage with it calling in parallel to john. But `clinfo` hangs until status line in john.

I scripted the process and collected data up to segfault.

Runner:
```
for i in `seq 255`; do sleep 5; echo; echo "START $i"; clinfo | grep 'Global.*memory'; echo "END1 clinfo $i"; DELAY=`expr 13 '*' "$i" - 5`; (sleep "$DELAY"; clinfo | grep 'Global.*memory'; echo "END2 clinfo $i") & ./jfix2/run/john --progress-every=1 --max-run-time="$DELAY" --format=descrypt-opencl t.pw --mask='[\x01-\xff][\x01-\xff][\x01-\xff][\x01-\x'"`printf '%02x' "$i"`"']?a?a?a' --lws=1 --gws=1 --mask-internal-target="`expr 255 '*' 255 '*' 255 '*' "$i"`"; echo "END john $i"; done
```

Formatter for output:
```
perl -0777 -e '$a = <>; @a = split /END john \d+/, $a; for (@a) { s/^[ \n]+//; die "no start after $i" if !/^START (\d+)/; $i = $1; die "no clinfo1 for i=$i" if !/Global memory size\s+(\d+).*END1 clinfo $i\n/s; $mem1 = $1; die "no lws/gws/x" if !/LWS=1 GWS=1 x(\d+)/; $x = $1; die "wrong x for $i" if $x != 255 * 255 * 255 * $i; die "no time for $i" if !/0g 0:(\d+:\d+:\d+) 0\./; $time = $1; die "no clinfo2 for i=$i" if !/END1 clinfo $i\n.*Global memory size\s+(\d+).*END2 clinfo $i\n/s; $mem2 = $1; printf "%2d %s %d %10d\n", $i, $time, $mem1, $mem1 - $mem2; }' < t.txt
```

Processed and annotated output:
```
 ,- x as in '255 * 255 * 255 * x' value for --mask-internal-target=
 | ,- john's run time in the first status line (with --progress-every=1)
 v v        mem before  mem used
 1 00:00:13 8543088640  350052352
 2 00:00:27 8543088640  686252032
 3 00:00:41 8543088640 1009844224
 4 00:00:55 8543088640 1331331072
 5 00:01:10 8543088640 1650720768
 6 00:01:22 8543088640 1974312960
 7 00:01:38 8543088640 2297905152
 8 00:01:51 8543088640 2617294848
 9 00:02:05 8543088640 2940887040
10 00:02:18 8543088640 3260276736
11 00:02:33 8543088640 3585974272
12 00:02:46 8543088640 3907461120
13 00:03:02 8543088640 4226850816
14 00:03:14 8543088640 4550443008
15 00:03:28 8543088640 4885098496
16 00:03:42 8529928192 5193424896
17 00:03:56 8529928192 5517017088
18 00:04:10 8529928192 5836406784
19 00:04:22 8529928192 6159998976
20 00:04:36 8535957504 6481494016
21 00:04:50 8535957504 6802980864
22 00:05:07 8535957504 7124475904
23 00:05:22 8535957504 7448068096
24 00:05:32 8535957504 7769554944
25 00:05:46 8535957504 8088944640
26 00:06:02 8535957504 8412536832 < only 117 mb of free mem left
27 00:06:18 8535957504 6721466368 < but then john used less memory
28 00:06:30 8557080576 6990675968
29 00:06:43 8557080576 7240867840
30 00:06:55 8557080576 7488954368
31 00:07:11 8557080576 7739146240
```

So john can hang for 7 minutes, but it is temporary. I could not make john to hang for real with the latest version of john.

`mem before` is not 100% stable. I don't know why. The experiment was done in one go right after a reboot.
